base_url = "https://dorname.github.io/"

default_language = "en"
compile_sass = true
title = "Keep learning and trying"
description = "主页"
generate_feed = false
output_dir = "docs"

taxonomies = [
  {name = "tags", paginate_by = 5},
  {name = "authors", paginate_by = 5},
]

build_search_index = true

[markdown]
highlight_code = true

[extra]
banner = "img/banner.jpeg"
date_format = '%d/%m/%Y'

theme = 'cyborg'
bg = "dark"
inverted = false

themes = "选择一个主题"
schemes = "选择一个Scheme颜色"
topics = "博客分类"
search = '搜索'
tag = 'Posts by Topic'
tags = '标签主题'

links = [
  {title = '作者', url = 'authors'},
	{title = '关于', url = 'about'},
	{title = '相关主题', url = 'tags'},
	{title = 'Github', url = 'https://github.com/dorname?tab=repositories'},
]
email = "lgqfighting@163.com"
icons = [
  {title = 'chatGPT', icon = 'glide-g', url = 'https://chat.openai.com/'},
  {title = '微信', icon = 'weixin', url = 'https://wx.qq.com/'},
  {title = '谷歌', icon = 'google', url = 'https://www.google.com/'}
]

utterances = ""
utterances_label = "Comments"
utterances_theme = "github-light"
utterances_issue_term = "pathname"

# Do not change this variables
data_themes = [
  'default',
  'cerulean',
  'cosmo',
  'cyborg',
  'darkly',
  'flatly',
  'journal',
  'litera',
  'lumen',
  'lux',
  'materia',
  'minty',
  'morph',
  'pulse',
  'quartz',
  'sandstone',
  'simplex',
  'sketchy',
  'slate',
  'solar',
  'spacelab',
  'superhero',
  'united',
  'vapor',
  'yeti',
  'zephyr'
]
data_schemes = [
  'dark',
  'light',
  'primary',
  'primary inverted',
  'secondary',
  'secondary inverted',
  'success',
  'success inverted',
  'danger',
  'danger inverted',
  'warning',
  'warning inverted',
  'info',
  'info inverted',
]
data_topics = [
  { title= "Rust学习", url="rust"},
  { title= "未分类博客",url = "articles"},
  { title = "js学习", url = "js_learning"},
  { title = "Extjs/Rust/WASM实验", url = "webAssembly_rust_and_extJs-lab"},
  { title = "区块链", url = "blockchain"},
  { title = "Mega", url = "mega_git"},
  { title = "分布式理论", url = "distributed_system"},
  { title = "Docker容器", url = "docker"},
  { title = "k8s", url = "kubernetes"},
  { title = "gradle", url = "gradle"},
  { title = "java", url = "java"}
]
