name = "zolastrap"
description = "A bootstrap theme for zola"
license = "MIT"
homepage = "https://github.com/marcodpt/zolastrap"
min_version = "0.14.1"
demo = "https://marcodpt.github.io/zolastrap/"

[author]
name = "Marco Tomic"
homepage = "https://marcodpt.github.io"

[extra]
banner = ""
date_format = '%d/%m/%Y'

theme = 'default'
bg = "dark"
inverted = false

themes = "Choose a Theme"
schemes = "Choose a Color Scheme"
search = 'Search'
tag = 'Posts by Topic'
tags = 'Posts by Topics'

links = []
email = ""
icons = []

utterances = ""
utterances_label = "Comments"
utterances_theme = "github-light"
utterances_issue_term = "pathname"

# Do not change this variables
data_themes = [
  'default',
  'cerulean',
  'cosmo',
  'cyborg',
  'darkly',
  'flatly',
  'journal',
  'litera',
  'lumen',
  'lux',
  'materia',
  'minty',
  'morph',
  'pulse',
  'quartz',
  'sandstone',
  'simplex',
  'sketchy',
  'slate',
  'solar',
  'spacelab',
  'superhero',
  'united',
  'vapor',
  'yeti',
  'zephyr'
]
data_schemes = [
  'dark',
  'light',
  'primary',
  'primary inverted',
  'secondary',
  'secondary inverted',
  'success',
  'success inverted',
  'danger',
  'danger inverted',
  'warning',
  'warning inverted',
  'info',
  'info inverted',
]
